using System.Text;
using System.Text.RegularExpressions;
using System.Xml;

namespace ShellUI.SafelistGenerator;

/// Scans .razor files for Tailwind utility classes and emits two artifacts:
///
///   1. wwwroot/shellui-classes.txt — flat sorted list (committed for drift detection
///      and used by the live ShellUI demo's own Tailwind build).
///
///   2. build/ShellUI.Components.targets — NuGet-auto-imported MSBuild file that
///      embeds every class in an <ItemGroup> and writes them out to the consumer's
///      wwwroot/ during build. Self-contained — no second NuGet file to extract.
///
/// Usage:
///   dotnet run --project tools/ShellUI.SafelistGenerator -- <razorDir> <txtOut> <targetsOut>
public static class Program
{
    public static int Main(string[] args)
    {
        if (args.Length != 3)
        {
            Console.Error.WriteLine("usage: ShellUI.SafelistGenerator <razor-dir> <txt-out> <targets-out>");
            return 1;
        }

        var razorDir = args[0];
        var txtOut = args[1];
        var targetsOut = args[2];

        if (!Directory.Exists(razorDir))
        {
            Console.Error.WriteLine($"razor directory not found: {razorDir}");
            return 2;
        }

        var razorFiles = Directory.GetFiles(razorDir, "*.razor", SearchOption.AllDirectories);
        var classes = GenerateSafelist(razorFiles);

        Directory.CreateDirectory(Path.GetDirectoryName(txtOut)!);
        File.WriteAllLines(txtOut, classes);

        Directory.CreateDirectory(Path.GetDirectoryName(targetsOut)!);
        File.WriteAllText(targetsOut, BuildTargetsFileContent(classes));

        Console.WriteLine($"wrote {classes.Count} classes from {razorFiles.Length} razor files");
        Console.WriteLine($"  txt:     {txtOut}");
        Console.WriteLine($"  targets: {targetsOut}");
        return 0;
    }

    /// Public for in-process testing — runs the same extraction the CLI invocation does.
    public static SortedSet<string> GenerateSafelist(IEnumerable<string> razorFilePaths)
    {
        var classes = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var file in razorFilePaths)
        {
            ExtractClasses(File.ReadAllText(file), classes);
        }
        return classes;
    }

    /// Public for in-process testing — produces the same .targets content the CLI writes.
    public static string BuildTargetsFileContent(IEnumerable<string> classes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<Project>");
        sb.AppendLine("  <!--");
        sb.AppendLine("    AUTO-GENERATED by tools/ShellUI.SafelistGenerator — do not edit by hand.");
        sb.AppendLine("    Regenerate via: dotnet run --project tools/ShellUI.SafelistGenerator -- \\");
        sb.AppendLine("        src/ShellUI.Components/Components \\");
        sb.AppendLine("        src/ShellUI.Components/wwwroot/shellui-classes.txt \\");
        sb.AppendLine("        src/ShellUI.Components/build/ShellUI.Components.targets");
        sb.AppendLine();
        sb.AppendLine("    NuGet auto-imports build/<PackageId>.targets into any consumer build. We");
        sb.AppendLine("    embed the Tailwind safelist inline so we don't depend on NuGet extracting");
        sb.AppendLine("    a second file (behavior varies by client/version). WriteLinesToFile drops");
        sb.AppendLine("    the list into the consumer's wwwroot/ so their input.css can:");
        sb.AppendLine("        @source \"./shellui-classes.txt\";");
        sb.AppendLine("  -->");
        sb.AppendLine("  <ItemGroup>");
        foreach (var cls in classes)
        {
            sb.Append("    <ShellUISafelistEntry Include=\"");
            sb.Append(XmlEscape(cls));
            sb.AppendLine("\" />");
        }
        sb.AppendLine("  </ItemGroup>");
        sb.AppendLine();
        sb.AppendLine("  <Target Name=\"WriteShellUISafelist\"");
        sb.AppendLine("          BeforeTargets=\"BeforeBuild;PrepareForBuild\"");
        sb.AppendLine("          Condition=\"'$(SkipShellUISafelist)' != 'true'\">");
        sb.AppendLine("    <MakeDir Directories=\"$(MSBuildProjectDirectory)/wwwroot\" Condition=\"!Exists('$(MSBuildProjectDirectory)/wwwroot')\" />");
        sb.AppendLine("    <WriteLinesToFile File=\"$(MSBuildProjectDirectory)/wwwroot/shellui-classes.txt\"");
        sb.AppendLine("                      Lines=\"@(ShellUISafelistEntry)\"");
        sb.AppendLine("                      Overwrite=\"true\" />");
        sb.AppendLine("  </Target>");
        sb.AppendLine("</Project>");
        return sb.ToString();
    }

    private static string XmlEscape(string s)
    {
        // We control the input (extracted Tailwind class strings) but `&` and `"` show
        // up in arbitrary values like data-[state=on] — escape conservatively.
        return s.Replace("&", "&amp;")
                .Replace("\"", "&quot;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;");
    }

    // Class-attribute extraction — handles literal strings, Razor expressions, nested
    // Shell.Cn("foo", …) literals. Razor variable parts (`@Class`) are dropped because
    // Tailwind would not see those at build time anyway.
    private static readonly Regex ClassAttributeRegex = new(
        "class\\s*=\\s*\"(?<value>[^\"]*)\"",
        RegexOptions.Compiled);

    private static readonly Regex StringLiteralRegex = new(
        "\"(?<lit>[^\"]*)\"",
        RegexOptions.Compiled);

    private static void ExtractClasses(string content, SortedSet<string> sink)
    {
        foreach (Match attr in ClassAttributeRegex.Matches(content))
        {
            var value = attr.Groups["value"].Value;
            HarvestTokens(value, sink);
            foreach (Match lit in StringLiteralRegex.Matches(value))
            {
                HarvestTokens(lit.Groups["lit"].Value, sink);
            }
        }
    }

    // A token qualifies as a Tailwind utility class if it contains at least one of
    // `-`, `:`, `[`, `/` AND starts with a lowercase letter. Excludes C# identifiers
    // (`Class`, `Variant`) caught by our literal extraction.
    private static void HarvestTokens(string text, SortedSet<string> sink)
    {
        var tokens = text.Split(new[] { ' ', '\t', '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries);
        foreach (var raw in tokens)
        {
            var token = raw.Trim();
            if (token.Length < 2) continue;
            if (!char.IsLower(token[0])) continue;
            if (!token.Contains('-') && !token.Contains(':') && !token.Contains('[') && !token.Contains('/')) continue;
            token = token.TrimEnd(',', ';', ')', '"');
            if (token.Length < 2) continue;
            sink.Add(token);
        }
    }
}
