using ShellUI.Core.Models;
using ShellUI.Templates.Templates;

namespace ShellUI.Templates;

public static class ComponentRegistry
{
    public static readonly Dictionary<string, ComponentMetadata> Components = new()
    {
        { "shell", ShellTemplate.Metadata },
        { "button", ButtonTemplate.Metadata },
        { "button-variants", ButtonVariantsTemplate.Metadata },
        { "theme-toggle", ThemeToggleTemplate.Metadata },
        { "input", InputTemplate.Metadata },
        { "card", CardTemplate.Metadata },
        { "card-header", CardHeaderTemplate.Metadata },
        { "card-title", CardTitleTemplate.Metadata },
        { "card-description", CardDescriptionTemplate.Metadata },
        { "card-content", CardContentTemplate.Metadata },
        { "card-footer", CardFooterTemplate.Metadata },
        { "alert", AlertTemplate.Metadata },
        { "badge", BadgeTemplate.Metadata },
        { "label", LabelTemplate.Metadata },
        { "textarea", TextareaTemplate.Metadata },
        { "dialog", DialogTemplate.Metadata },
        { "dialog-trigger", DialogTriggerTemplate.Metadata },
        { "dialog-content", DialogContentTemplate.Metadata },
        { "dialog-header", DialogHeaderTemplate.Metadata },
        { "dialog-footer", DialogFooterTemplate.Metadata },
        { "dialog-title", DialogTitleTemplate.Metadata },
        { "dialog-description", DialogDescriptionTemplate.Metadata },
        { "dialog-close", DialogCloseTemplate.Metadata },
        { "skeleton", SkeletonTemplate.Metadata },
        { "progress", ProgressTemplate.Metadata },
        { "separator", SeparatorTemplate.Metadata },
        { "select", SelectTemplate.Metadata },
        { "select-trigger", SelectTriggerTemplate.Metadata },
        { "select-content", SelectContentTemplate.Metadata },
        { "select-item", SelectItemTemplate.Metadata },
        { "checkbox", CheckboxTemplate.Metadata },
        { "switch", SwitchTemplate.Metadata },
        { "tabs", TabsTemplate.Metadata },
        { "tabs-list", TabsListTemplate.Metadata },
        { "tabs-trigger", TabsTriggerTemplate.Metadata },
        { "tabs-content", TabsContentTemplate.Metadata },
        { "tab-models", TabModelsTemplate.Metadata },
        { "navbar", NavbarTemplate.Metadata },
        { "sidebar", SidebarTemplate.Metadata },
        { "dropdown", DropdownTemplate.Metadata },
        { "dropdown-trigger", DropdownTriggerTemplate.Metadata },
        { "dropdown-content", DropdownContentTemplate.Metadata },
        { "dropdown-item", DropdownItemTemplate.Metadata },
        { "radio-group", RadioGroupTemplate.Metadata },
        { "radio-group-item", RadioGroupItemTemplate.Metadata },
        { "slider", SliderTemplate.Metadata },
        { "toggle", ToggleTemplate.Metadata },
        { "accordion", AccordionTemplate.Metadata },
        { "accordion-item", AccordionItemTemplate.Metadata },
        { "accordion-trigger", AccordionTriggerTemplate.Metadata },
        { "accordion-content", AccordionContentTemplate.Metadata },
        { "breadcrumb", BreadcrumbTemplate.Metadata },
        { "breadcrumb-item", BreadcrumbItemTemplate.Metadata },
        { "toast", ToastTemplate.Metadata },
        { "sonner", SonnerTemplate.Metadata },
        { "sonner-service", SonnerServiceTemplate.Metadata },
        { "sonner-variants", SonnerVariantsTemplate.Metadata },
        { "tooltip", TooltipTemplate.Metadata },
        { "popover", PopoverTemplate.Metadata },
        { "popover-trigger", PopoverTriggerTemplate.Metadata },
        { "popover-content", PopoverContentTemplate.Metadata },
        { "avatar", AvatarTemplate.Metadata },
        { "avatar-variants", AvatarVariantsTemplate.Metadata },
        { "badge-variants", BadgeVariantsTemplate.Metadata },
        { "alert-variants", AlertVariantsTemplate.Metadata },
        { "toggle-variants", ToggleVariantsTemplate.Metadata },
        { "table", TableTemplate.Metadata },
        { "table-header", TableHeaderTemplate.Metadata },
        { "table-body", TableBodyTemplate.Metadata },
        { "table-row", TableRowTemplate.Metadata },
        { "table-head", TableHeadTemplate.Metadata },
        { "table-cell", TableCellTemplate.Metadata },
        { "form", FormTemplate.Metadata },
        { "input-otp", InputOTPTemplate.Metadata },
        { "combobox", ComboboxTemplate.Metadata },
        { "date-picker", DatePickerTemplate.Metadata },
        { "date-range-picker", DateRangePickerTemplate.Metadata },
        { "time-picker", TimePickerTemplate.Metadata },
        { "navigation-menu", NavigationMenuTemplate.Metadata },
        { "nav-list", NavListTemplate.Metadata },
        { "nav-item", NavItemTemplate.Metadata },
        { "nav-trigger", NavTriggerTemplate.Metadata },
        { "nav-content", NavContentTemplate.Metadata },
        { "navigation-menu-item", NavigationMenuItemTemplate.Metadata },
        { "menubar", MenubarTemplate.Metadata },
        { "menubar-item", MenubarItemTemplate.Metadata },
        { "pagination", PaginationTemplate.Metadata },
        { "scroll-area", ScrollAreaTemplate.Metadata },
        { "resizable", ResizableTemplate.Metadata },
        { "sheet", SheetTemplate.Metadata },
        { "drawer", DrawerTemplate.Metadata },
        { "collapsible", CollapsibleTemplate.Metadata },
        { "collapsible-trigger", CollapsibleTriggerTemplate.Metadata },
        { "collapsible-content", CollapsibleContentTemplate.Metadata },
        { "data-table", DataTableTemplate.Metadata },
        { "alert-dialog", AlertDialogTemplate.Metadata },
        { "calendar", CalendarTemplate.Metadata },
        { "loading", LoadingTemplate.Metadata },
        { "hover-card", HoverCardTemplate.Metadata },
        { "hover-card-trigger", HoverCardTriggerTemplate.Metadata },
        { "hover-card-content", HoverCardContentTemplate.Metadata },
        { "command", CommandTemplate.Metadata },
        { "context-menu", ContextMenuTemplate.Metadata },
        { "context-menu-trigger", ContextMenuTriggerTemplate.Metadata },
        { "context-menu-content", ContextMenuContentTemplate.Metadata },
        { "context-menu-option", ContextMenuOptionTemplate.Metadata },
        { "empty-state", EmptyStateTemplate.Metadata },
        { "stepper", StepperTemplate.Metadata },
        { "stepper-list", StepperListTemplate.Metadata },
        { "stepper-step", StepperStepTemplate.Metadata },
        { "stepper-content", StepperContentTemplate.Metadata },
        { "carousel", CarouselTemplate.Metadata },
        { "carousel-list", CarouselListTemplate.Metadata },
        { "carousel-slide", CarouselSlideTemplate.Metadata },
        { "carousel-item", CarouselItemTemplate.Metadata },
        { "carousel-content", CarouselContentTemplate.Metadata },
        { "carousel-previous", CarouselPreviousTemplate.Metadata },
        { "carousel-next", CarouselNextTemplate.Metadata },
        { "carousel-dots", CarouselDotsTemplate.Metadata },
        { "file-upload", FileUploadTemplate.Metadata },
        { "chart-variants", ChartVariantsTemplate.Metadata },
        { "chart", ChartTemplate.Metadata },
        { "bar-chart", BarChartTemplate.Metadata },
        { "line-chart", LineChartTemplate.Metadata },
        { "pie-chart", PieChartTemplate.Metadata },
        { "area-chart", AreaChartTemplate.Metadata },
        { "multi-series-chart", MultiSeriesChartTemplate.Metadata },
        { "chart-series", ChartSeriesTemplate.Metadata },
        { "copy-button", CopyButtonTemplate.Metadata },
        { "callout-variants", CalloutVariantsTemplate.Metadata },
        { "callout", CalloutTemplate.Metadata },
        { "link-card", LinkCardTemplate.Metadata },
        { "prev-next-nav", PrevNextNavTemplate.Metadata }
    };

    public static string? GetComponentContent(string componentName)
    {
        return componentName.ToLower() switch
        {
            "shell" => ShellTemplate.Content,
            "button" => ButtonTemplate.Content,
            "button-variants" => ButtonVariantsTemplate.Content,
            "theme-toggle" => ThemeToggleTemplate.Content,
            "input" => InputTemplate.Content,
            "card" => CardTemplate.Content,
            "card-header" => CardHeaderTemplate.Content,
            "card-title" => CardTitleTemplate.Content,
            "card-description" => CardDescriptionTemplate.Content,
            "card-content" => CardContentTemplate.Content,
            "card-footer" => CardFooterTemplate.Content,
            "alert" => AlertTemplate.Content,
            "badge" => BadgeTemplate.Content,
            "label" => LabelTemplate.Content,
            "textarea" => TextareaTemplate.Content,
            "dialog" => DialogTemplate.Content,
            "dialog-trigger" => DialogTriggerTemplate.Content,
            "dialog-content" => DialogContentTemplate.Content,
            "dialog-header" => DialogHeaderTemplate.Content,
            "dialog-footer" => DialogFooterTemplate.Content,
            "dialog-title" => DialogTitleTemplate.Content,
            "dialog-description" => DialogDescriptionTemplate.Content,
            "dialog-close" => DialogCloseTemplate.Content,
            "skeleton" => SkeletonTemplate.Content,
            "progress" => ProgressTemplate.Content,
            "separator" => SeparatorTemplate.Content,
            "select" => SelectTemplate.Content,
            "select-trigger" => SelectTriggerTemplate.Content,
            "select-content" => SelectContentTemplate.Content,
            "select-item" => SelectItemTemplate.Content,
            "checkbox" => CheckboxTemplate.Content,
            "switch" => SwitchTemplate.Content,
            "tabs" => TabsTemplate.Content,
            "tabs-list" => TabsListTemplate.Content,
            "tabs-trigger" => TabsTriggerTemplate.Content,
            "tabs-content" => TabsContentTemplate.Content,
            "tab-models" => TabModelsTemplate.Content,
            "navbar" => NavbarTemplate.Content,
            "sidebar" => SidebarTemplate.Content,
            "dropdown" => DropdownTemplate.Content,
            "dropdown-trigger" => DropdownTriggerTemplate.Content,
            "dropdown-content" => DropdownContentTemplate.Content,
            "dropdown-item" => DropdownItemTemplate.Content,
            "radio-group" => RadioGroupTemplate.Content,
            "radio-group-item" => RadioGroupItemTemplate.Content,
            "slider" => SliderTemplate.Content,
            "toggle" => ToggleTemplate.Content,
            "accordion" => AccordionTemplate.Content,
            "accordion-item" => AccordionItemTemplate.Content,
            "accordion-trigger" => AccordionTriggerTemplate.Content,
            "accordion-content" => AccordionContentTemplate.Content,
            "breadcrumb" => BreadcrumbTemplate.Content,
            "breadcrumb-item" => BreadcrumbItemTemplate.Content,
            "toast" => ToastTemplate.Content,
            "sonner" => SonnerTemplate.Content,
            "sonner-service" => SonnerServiceTemplate.Content,
            "sonner-variants" => SonnerVariantsTemplate.Content,
            "tooltip" => TooltipTemplate.Content,
            "popover" => PopoverTemplate.Content,
            "popover-trigger" => PopoverTriggerTemplate.Content,
            "popover-content" => PopoverContentTemplate.Content,
            "avatar" => AvatarTemplate.Content,
            "avatar-variants" => AvatarVariantsTemplate.Content,
            "badge-variants" => BadgeVariantsTemplate.Content,
            "alert-variants" => AlertVariantsTemplate.Content,
            "toggle-variants" => ToggleVariantsTemplate.Content,
            "table" => TableTemplate.Content,
            "table-header" => TableHeaderTemplate.Content,
            "table-body" => TableBodyTemplate.Content,
            "table-row" => TableRowTemplate.Content,
            "table-head" => TableHeadTemplate.Content,
            "table-cell" => TableCellTemplate.Content,
            "form" => FormTemplate.Content,
            "input-otp" => InputOTPTemplate.Content,
            "combobox" => ComboboxTemplate.Content,
            "date-picker" => DatePickerTemplate.Content,
            "date-range-picker" => DateRangePickerTemplate.Content,
            "time-picker" => TimePickerTemplate.Content,
            "navigation-menu" => NavigationMenuTemplate.Content,
            "nav-list" => NavListTemplate.Content,
            "nav-item" => NavItemTemplate.Content,
            "nav-trigger" => NavTriggerTemplate.Content,
            "nav-content" => NavContentTemplate.Content,
            "navigation-menu-item" => NavigationMenuItemTemplate.Content,
            "menubar" => MenubarTemplate.Content,
            "menubar-item" => MenubarItemTemplate.Content,
            "pagination" => PaginationTemplate.Content,
            "scroll-area" => ScrollAreaTemplate.Content,
            "resizable" => ResizableTemplate.Content,
            "sheet" => SheetTemplate.Content,
            "drawer" => DrawerTemplate.Content,
            "collapsible" => CollapsibleTemplate.Content,
            "collapsible-trigger" => CollapsibleTriggerTemplate.Content,
            "collapsible-content" => CollapsibleContentTemplate.Content,
            "data-table" => DataTableTemplate.Content,
            "alert-dialog" => AlertDialogTemplate.Content,
            "calendar" => CalendarTemplate.Content,
            "loading" => LoadingTemplate.Content,
            "hover-card" => HoverCardTemplate.Content,
            "hover-card-trigger" => HoverCardTriggerTemplate.Content,
            "hover-card-content" => HoverCardContentTemplate.Content,
            "command" => CommandTemplate.Content,
            "context-menu" => ContextMenuTemplate.Content,
            "context-menu-trigger" => ContextMenuTriggerTemplate.Content,
            "context-menu-content" => ContextMenuContentTemplate.Content,
            "context-menu-option" => ContextMenuOptionTemplate.Content,
            "empty-state" => EmptyStateTemplate.Content,
            "stepper" => StepperTemplate.Content,
            "stepper-list" => StepperListTemplate.Content,
            "stepper-step" => StepperStepTemplate.Content,
            "stepper-content" => StepperContentTemplate.Content,
            "carousel" => CarouselTemplate.Content,
            "carousel-list" => CarouselListTemplate.Content,
            "carousel-slide" => CarouselSlideTemplate.Content,
            "carousel-item" => CarouselItemTemplate.Content,
            "carousel-content" => CarouselContentTemplate.Content,
            "carousel-previous" => CarouselPreviousTemplate.Content,
            "carousel-next" => CarouselNextTemplate.Content,
            "carousel-dots" => CarouselDotsTemplate.Content,
            "file-upload" => FileUploadTemplate.Content,
            "chart-variants" => ChartVariantsTemplate.Content,
            "chart" => ChartTemplate.Content,
            "bar-chart" => BarChartTemplate.Content,
            "line-chart" => LineChartTemplate.Content,
            "pie-chart" => PieChartTemplate.Content,
            "area-chart" => AreaChartTemplate.Content,
            "multi-series-chart" => MultiSeriesChartTemplate.Content,
            "chart-series" => ChartSeriesTemplate.Content,
            "copy-button" => CopyButtonTemplate.Content,
            "callout-variants" => CalloutVariantsTemplate.Content,
            "callout" => CalloutTemplate.Content,
            "link-card" => LinkCardTemplate.Content,
            "prev-next-nav" => PrevNextNavTemplate.Content,
            _ => null
        };
    }

    public static IEnumerable<ComponentMetadata> GetByCategory(ComponentCategory category)
    {
        return Components.Values.Where(c => c.Category == category);
    }

    public static IEnumerable<ComponentMetadata> SearchByTag(string tag)
    {
        return Components.Values.Where(c => c.Tags.Contains(tag, StringComparer.OrdinalIgnoreCase));
    }

    public static ComponentMetadata? GetMetadata(string componentName)
    {
        return Components.TryGetValue(componentName.ToLower(), out var metadata) ? metadata : null;
    }

    public static bool Exists(string componentName)
    {
        return Components.ContainsKey(componentName.ToLower());
    }
}

