namespace ShellUI.Templates;

public static class CssTemplates
{
    public static string InputCss => @"@tailwind base;
@tailwind components;
@tailwind utilities;

/*
 * ShellUI - Customize your theme here!
 *
 * Add your color variables and theme customizations below.
 * These will be processed by the Tailwind standalone CLI.
 *
 * Example:
 *
 * @theme {
 *   --color-primary: #3b82f6;
 *   --color-secondary: #64748b;
 * }
 */
";

    public static string AppCss => @"/*
 * ShellUI - Blazor Component Library
 * Generated by: dotnet shellui init
 *
 * This file is auto-generated by Tailwind CLI.
 * Do NOT edit this file directly - edit wwwroot/input.css instead.
 */

/* Tailwind will generate the final CSS here */
";

    public static string TailwindConfigJs => @"/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './Components/**/*.{razor,html,cshtml}',
    './Pages/**/*.{razor,html,cshtml}',
  ],
  darkMode: 'class',
  theme: {
    extend: {},
  },
}
";
}