using ShellUI.Core.Models;
using ShellUI.Templates;
using System.Text.Json;
using Spectre.Console;

namespace ShellUI.CLI.Services;

public class InitService
{
    public static async Task InitializeAsync(string style, bool force)
    {
        var configPath = Path.Combine(Directory.GetCurrentDirectory(), "shellui.json");
        
        if (File.Exists(configPath) && !force)
        {
            AnsiConsole.MarkupLine("[yellow]ShellUI is already initialized in this project.[/]");
            AnsiConsole.MarkupLine("[dim]Use --force to reinitialize[/]");
            return;
        }

        // Step 1: Detect project
        AnsiConsole.MarkupLine("[cyan]Initializing ShellUI...[/]");
        var projectInfo = ProjectDetector.DetectProject();
        AnsiConsole.MarkupLine($"[green]Detected:[/] {projectInfo.ProjectType}");
        AnsiConsole.MarkupLine($"[dim]Project: {projectInfo.ProjectName}[/]");
        AnsiConsole.MarkupLine($"[dim]Namespace: {projectInfo.RootNamespace}[/]");

        // Step 2: Create Components/UI folder
        AnsiConsole.MarkupLine("[cyan]Creating component folders...[/]");
        var componentsPath = Path.Combine(Directory.GetCurrentDirectory(), "Components", "UI");
        Directory.CreateDirectory(componentsPath);
        AnsiConsole.MarkupLine($"[green]Created:[/] Components/UI/");

        // Step 3: Create shellui.json
        AnsiConsole.MarkupLine("[cyan]Creating configuration...[/]");
        var config = new ShellUIConfig
        {
            Style = style,
            ComponentsPath = "Components/UI",
            ProjectType = projectInfo.ProjectType,
            Tailwind = new TailwindConfig
            {
                Enabled = true,
                Version = "4.1.0",
                CssPath = "wwwroot/app.css"
            }
        };

        var json = JsonSerializer.Serialize(config, new JsonSerializerOptions
        {
            WriteIndented = true
        });
        File.WriteAllText(configPath, json);
        AnsiConsole.MarkupLine($"[green]Created:[/] shellui.json");

        // Step 4: Create _Imports.razor if it doesn't exist
        AnsiConsole.MarkupLine("[cyan]Setting up imports...[/]");
        var importsPath = Path.Combine(Directory.GetCurrentDirectory(), "Components", "_Imports.razor");
        if (File.Exists(importsPath))
        {
            var importsContent = File.ReadAllText(importsPath);
            var usingStatement = $"@using {projectInfo.RootNamespace}.Components.UI";

            if (!importsContent.Contains(usingStatement))
            {
                File.AppendAllText(importsPath, $"\n{usingStatement}\n");
                AnsiConsole.MarkupLine($"[green]Updated:[/] Components/_Imports.razor");
            }
        }

        // Step 5: Download Tailwind CLI (no Node.js required!)
        AnsiConsole.MarkupLine("[cyan]Downloading Tailwind CSS standalone CLI...[/]");
        var tailwindPath = await TailwindDownloader.EnsureTailwindCliAsync(Directory.GetCurrentDirectory());

        // Step 6: Create CSS files
        AnsiConsole.MarkupLine("[cyan]Creating CSS files...[/]");
        var wwwrootPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");
        Directory.CreateDirectory(wwwrootPath);

        // Create input.css with design tokens
        var inputCssPath = Path.Combine(wwwrootPath, "input.css");
        File.WriteAllText(inputCssPath, CssTemplates.InputCss);
        AnsiConsole.MarkupLine($"[green]Created:[/] wwwroot/input.css");

        // Create placeholder app.css (will be generated by Tailwind)
        var appCssPath = Path.Combine(wwwrootPath, "app.css");
        File.WriteAllText(appCssPath, CssTemplates.AppCss);
        AnsiConsole.MarkupLine($"[green]Created:[/] wwwroot/app.css");

        // Create tailwind.config.js
        var tailwindConfigPath = Path.Combine(Directory.GetCurrentDirectory(), "tailwind.config.js");
        File.WriteAllText(tailwindConfigPath, CssTemplates.TailwindConfigJs);
        AnsiConsole.MarkupLine($"[green]Created:[/] tailwind.config.js");

        // Step 7: Create MSBuild targets file
        AnsiConsole.MarkupLine("[cyan]Setting up MSBuild integration...[/]");
        var buildPath = Path.Combine(Directory.GetCurrentDirectory(), "Build");
        Directory.CreateDirectory(buildPath);

        var targetsPath = Path.Combine(buildPath, "ShellUI.targets");
        var targetsContent = GetTargetsFileContent();
        File.WriteAllText(targetsPath, targetsContent);
        AnsiConsole.MarkupLine($"[green]Created:[/] Build/ShellUI.targets");

        // Update .csproj to import targets
        await UpdateProjectFileAsync(projectInfo.ProjectPath, targetsPath);
        AnsiConsole.MarkupLine($"[green]Updated:[/] {Path.GetFileName(projectInfo.ProjectPath)}");

        // Step 8: Run initial Tailwind build
        AnsiConsole.MarkupLine("[cyan]Building Tailwind CSS...[/]");
        await RunTailwindBuildAsync(tailwindPath, inputCssPath, appCssPath);
        AnsiConsole.MarkupLine($"[green]Built:[/] Tailwind CSS");

        AnsiConsole.MarkupLine("\n[green]ShellUI initialized successfully![/]");
        AnsiConsole.MarkupLine("\n[blue]Next steps:[/]");
        AnsiConsole.MarkupLine("  [dim]1. Add components:[/] dotnet shellui add button");
        AnsiConsole.MarkupLine("  [dim]2. Browse all:[/] dotnet shellui list");
    }

    private static async Task RunTailwindBuildAsync(string tailwindPath, string inputPath, string outputPath)
    {
        var startInfo = new System.Diagnostics.ProcessStartInfo
        {
            FileName = tailwindPath,
            Arguments = $"-i \"{inputPath}\" -o \"{outputPath}\" --minify",
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        using var process = System.Diagnostics.Process.Start(startInfo);
        if (process == null)
        {
            throw new Exception("Failed to start Tailwind CSS process");
        }

        await process.WaitForExitAsync();

        if (process.ExitCode != 0)
        {
            var error = await process.StandardError.ReadToEndAsync();
            throw new Exception($"Tailwind CSS build failed: {error}");
        }
    }

    private static string GetTargetsFileContent()
    {
        return @"<?xml version=""1.0"" encoding=""utf-8""?>
<Project>
  <PropertyGroup>
    <ShellUIBinPath Condition=""'$(ShellUIBinPath)' == ''"">$(MSBuildProjectDirectory)\.shellui\bin</ShellUIBinPath>
    <TailwindExecutable Condition=""'$(OS)' == 'Windows_NT'"">$(ShellUIBinPath)\tailwindcss.exe</TailwindExecutable>
    <TailwindExecutable Condition=""'$(OS)' != 'Windows_NT'"">$(ShellUIBinPath)/tailwindcss</TailwindExecutable>
    <TailwindInputCss Condition=""'$(TailwindInputCss)' == ''"">$(MSBuildProjectDirectory)\wwwroot\input.css</TailwindInputCss>
    <TailwindOutputCss Condition=""'$(TailwindOutputCss)' == ''"">$(MSBuildProjectDirectory)\wwwroot\app.css</TailwindOutputCss>
    <TailwindMinify Condition=""'$(Configuration)' == 'Release'"">--minify</TailwindMinify>
    <TailwindMinify Condition=""'$(Configuration)' != 'Release'""></TailwindMinify>
  </PropertyGroup>

  <Target Name=""BuildTailwindCSS"" BeforeTargets=""BeforeBuild"" Condition=""Exists('$(TailwindExecutable)') AND Exists('$(TailwindInputCss)')"">
    <Message Importance=""high"" Text=""Building Tailwind CSS..."" />
    <Exec Command=""&quot;$(TailwindExecutable)&quot; -i &quot;$(TailwindInputCss)&quot; -o &quot;$(TailwindOutputCss)&quot; $(TailwindMinify)"" />
    <Message Importance=""high"" Text=""Tailwind CSS built successfully!"" />
  </Target>

  <Target Name=""CleanTailwindCSS"" AfterTargets=""Clean"" Condition=""Exists('$(TailwindOutputCss)')"">
    <Message Importance=""high"" Text=""Cleaning Tailwind CSS output..."" />
    <Delete Files=""$(TailwindOutputCss)"" />
  </Target>
</Project>";
    }

    private static async Task UpdateProjectFileAsync(string projectFilePath, string targetsPath)
    {
        var content = await File.ReadAllTextAsync(projectFilePath);
        var targetsImport = $"  <Import Project=\"Build\\ShellUI.targets\" />";

        // Check if import already exists
        if (content.Contains(targetsImport) || content.Contains("ShellUI.targets"))
        {
            return;
        }

        // Insert before closing </Project> tag
        var closingTag = "</Project>";
        var insertIndex = content.LastIndexOf(closingTag);
        
        if (insertIndex > 0)
        {
            content = content.Insert(insertIndex, targetsImport + Environment.NewLine + Environment.NewLine);
            await File.WriteAllTextAsync(projectFilePath, content);
        }
    }
}

